### ISSUE TITLE
API with JSON Output

### ISSUE THREAD

**Issue by StefanS-O** [StefanS-O/jupiterbroadcasting-hugo-mvp#4]
make all content also available via JSON

**Comment by StefanS-O** [comment]
This is more important now, since i need it for the Podlove Webplayer

**Comment by kbondarev** [comment]
@StefanS-O Since I'm already scraping all the content in the scraper script and putting outputing everything into the `.md` files, I could also generate a bunch of `json` files for each episode.

Is [this the format](https://docs.podlove.org/podlove-web-player/v5/configuration) we're looking for? Where should these files go?

**Comment by StefanS-O** [comment]
This needs to happen as part of the Hugo build process, because we also need it for later, when we create new content only through Hugo. These files would go into to the generated folder, next to the index.html. The currently existing template for the player can be found here:

https://github.com/StefanS-O/jupiterbroadcasting-hugo-mvp/blob/main/themes/jb/layouts/episode/single.json

**Comment by kbondarev** [comment]
Oh I get it now. Hugo is pretty cool...
It's basically this: https://gohugo.io/templates/output-formats/
